
parameters:

services:

    _defaults:
        autowire: true      
        autoconfigure: true 

   
    App\:
        resource: '../src/'


    App\Service\EmailService:
        arguments:
            $appUrl: '%env(APP_URL)%'
            $mailerFrom: '%env(MAILER_FROM)%'

  
